Hotfix validation
chitan148/TimesavingsBank pull request #19
Opened 2021-04-07 01:40 UTC by chitan148

フロントのバリデーション貼れたと思うので、確認とレビューお願い致します。

2021-04-08 11:17 UTC, junmoka requested changes
確認お願いします

2021-04-08 11:17 UTC, junmoka commented on resources/views/auth/register.blade.php
> +                    <input type="password" class="form-control font-default" id="password-confirm" name="password_confirmation" required tabindex="4">
password-confirmのminlengthはなくて大丈夫？

2021-04-08 11:17 UTC, junmoka commented on resources/views/share/eventlistener/scripts_for_password_confirm.blade.php
> +    passwordConfirm.addEventListener('input',function(){
動作確認できてないけど、先にconfirm入れた場合にちゃんと動く？

2021-04-08 11:23 UTC, chitan148 commented on resources/views/share/eventlistener/scripts_for_password_confirm.blade.php
> +    passwordConfirm.addEventListener('input',function(){
先にconfirm側入れてみましたが、送信を押したらsetCustomValidity()に設定したメッセージちゃんとでてきました。

2021-04-08 11:29 UTC, chitan148 commented on resources/views/auth/register.blade.php
> +                    <input type="password" class="form-control font-default" id="password-confirm" name="password_confirmation" required tabindex="4">
ありがとうございます。minlength追加しました！

2021-04-11 03:13 UTC, junmoka approved these changes

2021-04-11 03:20 UTC, merged